#!/bin/bash

usage()
{
	echo "usage: cue2alac <cuefile>"
}

program_exists ()
{
	type "$1" &> /dev/null ;
}

metadata()
{
	local cue_file="$1"
	local field="$2"
	echo `cueprint -n $track -t "$field" "$cue_file"`
}

convert()
{
	local cue_file="$1"
	local track=$2
	local infile="$3"
	local date="$4"
	local genre="$5"
	local outfile="${infile/%flac/m4a}"

	local album_artist="$(metadata "$cue_file" "%P")"
	local artist="$(metadata "$cue_file" "%p")"

	if [ -z "$artist" ] && [ -n "$album_artist" ]; then
		artist="$album_artist"
		album_artist=""
	fi

	echo "Converting $infile to $outfile ..."

	ffmpeg -v error -i "$infile" -acodec alac \
		-metadata title="$(metadata "$cue_file" "%t")" \
		-metadata artist="$artist" \
		-metadata album_artist="$album_artist" \
		-metadata album="$(metadata "$cue_file" "%T")" \
		-metadata composer="$(metadata "$cue_file" "%c")" \
		-metadata date="$date" \
		-metadata track="$track" \
		-metadata genre="$genre" \
		"$outfile"
}

main()
{
	set -e

	if ! program_exists ffmpeg; then
		echo "Please install ffmpeg"
		exit 1
	fi

	if ! program_exists metaflac; then
		echo "Please install flac"
		exit 1
	fi

	if ! program_exists shnsplit; then
		echo "Please install shntool"
		exit 1
	fi

	if [ -z "$1" ]; then
		usage
		exit
	fi

	local cue_file="$1"
	local music_file=`sed -n 's#^FILE "\(.*\)".*$#\1#p' "$cue_file"`
	local date=`sed -n -e 's#^REM DATE \(.*\)$#\1#p' "$cue_file"`
	date=`echo "$date" | sed 's#\"##g'`
	local genre=`sed -n -e 's#^REM GENRE \(.*\)#\1#p' "$cue_file"`
	genre=`echo $genre | sed 's#\"##g'`

	mkdir -p tmp

	ext=`echo "${music_file: -4}" | tr "[:upper:]" "[:lower:]"`
	if [ "$ext" == ".ape" ]; then
		local music_file_tmp="${music_file/%ape/flac}"
		echo "Converting $music_file to $music_file_tmp ..."
		ffmpeg -v warning -i "$music_file" "tmp/$music_file_tmp"
		music_file="$music_file_tmp"
	else
		music_file="../$music_file"
	fi

	cd tmp

	shnsplit -f "../$cue_file" -o flac -t '%n %t' "$music_file"

	if [ -n "$music_file_tmp" ]; then
		echo "Removing temporary file $music_file_tmp ..."
		rm -rf "$music_file_tmp"
	fi

	local trackno=1

	for file in *.flac; do
		convert "../$cue_file" $trackno "$file" "$date" "$genre"
		trackno=$(($trackno + 1))
	done

	echo "Removing temporary files ..."
	mv *.m4a ..
	cd ..
	rm -rf tmp

	echo "Done!"
}

main "$@"

